### ISSUE TITLE
Invalid pronouns

### ISSUE THREAD

**Issue by DikeKike** [ashhhleyyy/player-pronouns#8]
https://stallman.org/articles/genderless-pronouns.html
"They" is a plural pronoun.
Please refrain from mutilating the english language, thank you.
The same goes for the other 74092629458 made-up words.
Pronouns in english are chosen based on someones sex; his chromosomes.
If his sex is unknown, "he" is used by default.

**Comment by ashhhleyyy** [comment]
Understand that is factually incorrect: https://www.merriam-webster.com/words-at-play/singular-nonbinary-they

Please leave this issue tracker, bigot

**Comment by cyxv** [comment]
> https://stallman.org/articles/genderless-pronouns.html
DikeKike did you even read the article before citing it lmao, it's not a bad article but you completely missed the point, Stallman is literally advocating for gender neutral language, just with a better replacement

either way they has been used as a singular pronoun for centuries and if you argue otherwise you probably failed elementary school English

**Comment by bioastroiner** [comment]
> "They" is a plural pronoun.
https://public.oed.com/blog/a-brief-history-of-singular-they/
![image](https://user-images.githubusercontent.com/68257484/183332609-abbe1572-5bf7-4a3a-803f-51fce2abc771.png)
